---
branches: master

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: ./gradlew verifyNoSnapshotDependencies
      publishCmd: RELEASE=true ./gradlew showVersion verifyReleaseVersion $PUBLISH_TASKS
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
  - - "@semantic-release/github"
    - assets:
      - build/distributions/*
