name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@11ac55c836e622b4a3c944e057f9067cfdc6ab11 # v4.1.1
    with:
      java-version: 17

  docker:
    uses: wetransform/gha-workflows/.github/workflows/gradle-service-check.yml@11ac55c836e622b4a3c944e057f9067cfdc6ab11 # v4.1.1
    with:
      java-version: 17
      image-tag: wetransform/hale-cli:latest # image to scan
      # don't run tests since this is already done in check
      gradle-tasks: clean dockerTagLatest
      expect-tests: false
