name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

concurrency:
  # only run one publishing at a time to avoid conflicts in artifactory
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  artifacts:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library.yml@61717b8c3687e36efffa44e2e405f477e2be2323 # v3.1.1
    with:
      java-version: 17
      build-tasks: clean check distZip buildDeb
      publish-tasks: publish
      upload-artifact-path: build/distributions
      upload-artifact-name: distributions
    secrets:
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}

  docker:
    uses: wetransform/gha-workflows/.github/workflows/gradle-service-publish.yml@61717b8c3687e36efffa44e2e405f477e2be2323 # v3.1.1
    with:
      java-version: 17
      image-tag: wetransform/hale-cli:latest # image to scan
      # don't run tests since this is already done in artifacts
      build-tasks: clean
      publish-tasks: dockerPushImage
      expect-tests: false
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
