---
name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
        default: false

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  release:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@39472b0820006f75ebd19b348939b163d7bd8a6a # v3.3.2
    with:
      java-version: 17
      build-tasks: clean check
      publish-tasks: distZip buildDeb publish # performed after setting release version
      multi-module: false
      semantic-release: true
      semantic-release-dryrun: ${{ inputs.dryRun }}
    secrets:
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
      WE_RELEASE_GITHUB_APP_ID: ${{ secrets.WE_RELEASE_GITHUB_APP_ID }}
      WE_RELEASE_GITHUB_PRIVATE_KEY: ${{ secrets.WE_RELEASE_GITHUB_PRIVATE_KEY }}

  docker:
    needs: [release]
    if: ${{ needs.release.outputs.release-published != 'false' && needs.release.outputs.release-published != '' }}
    uses: wetransform/gha-workflows/.github/workflows/gradle-service-publish.yml@39472b0820006f75ebd19b348939b163d7bd8a6a # v3.3.2
    with:
      checkout-ref: refs/tags/v${{needs.release.outputs.release-version}} # check out release tag
      java-version: 17
      image-tag: wetransform/hale-cli:latest # image to scan
      # don't run tests since this is already done in artifacts
      build-tasks: clean
      publish-tasks: dockerPushImage
      expect-tests: false
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
