---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Run pre-commit hook checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  check-hooks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # fetch all history so checks (e.g. gitleaks) can check the full history
          fetch-depth: 0

      - name: Set up mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run checks
        run: |
          hk check --all
        env:
          MISE_ENV: ci
          # specify profile for CI check where all files are checked
          HK_PROFILE: ci-check-all
          # required for some builds, set if available
          GH_PAT: ${{ secrets.GH_PAT }}
