---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Run pre-commit hook checks

on:
  pull_request:
    branches:
      - "*"

jobs:
  check-hooks:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # fetch all history so checks (e.g. gitleaks) can check the full history
          fetch-depth: 0

      - name: Set up mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Run checks
        run: |
          hk check --all
        env:
          MISE_ENV: ci
          # specify profile for CI check where all files are checked
          HK_PROFILE: ci-check-all
          # required for some builds, set if available
          GH_PAT: ${{ secrets.GH_PAT }}
